defaults: &defaults
  working_directory: ~/circleci-test
  docker:
    - image: circleci/node:6.11.5

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-test
      - run:
          name: Install global tools
          command: sudo npm i -g typescript
      - run:
          name: Restore dependencies
          command: npm i
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/circleci-test
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
  publish_next:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/circleci-test
      - run:
          name: Publish @next
          command: npm publish --tag next
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/circleci-test
      - run:
          name: Publish
          command: npm publish
  build_docs:
    docker:
      - image: circleci/python:2.7.11
    steps:
      - attach_workspace:
          at: ~/circleci-test
      - run:
          name: Install MkDocs
          command: pip install mkdocs
      - run:
          name: Build docs
          command: mkdocs build

workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish_next:
          filters:
            branches:
              only: dev
      - publish:
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
      - build_docs:
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/