defaults: &defaults
  working_directory: /tmp
  docker:
    - image: circleci/node:6.11.5

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install global tools
          command: sudo npm i -g typescript
      - run:
          name: Restore dependencies
          command: npm i
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ./
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: Install global tools
          command: sudo npm i -g istanbul
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build