defaults: &defaults
  working_directory: ~/circleci-test
  docker:
    - image: circleci/node:6.11.5

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-test
      - run:
          name: Install global tools
          command: sudo npm i -g typescript
      - run:
          name: Restore dependencies
          command: npm i
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/circleci-test
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
  publish_next:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/circleci-test
      - run:
          name: Write .npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish @next
          command: echo "npm publish --tag next"
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/circleci-test
      - run:
          name: Write .npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish
          command: echo "npm publish"
  deploy_docs:
    working_directory: ~/circleci-test/docs
    docker:
      - image: circleci/python:2.7-jessie-node
    steps:
      - attach_workspace:
          at: ~/circleci-test
      - run:
          name: Install MkDocs
          command: sudo pip install mkdocs
      - run:
          name: Build docs
          command: mkdocs gh-deploy

workflows:
  version: 2
  release:
    jobs:
      - build:
          filters:
#            branches:
#              only: master
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
#  release:
#    jobs:
#      - build:
#          filters:
#            branches:
#              only: master
#            tags:
#              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
#      - test:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master
#            tags:
#              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
#      - publish:
#          requires:
#            - test
#          filters:
#            branches:
#              only: master
#            tags:
#              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
#      - deploy_docs:
#          requires:
#            - publish
#          filters:
#            branches:
#              only: master
#            tags:
#              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
#  release_next:
#    jobs:
#      - build:
#          filters:
#            branches:
#              only: dev
#      - test:
#          requires:
#            - build
#          filters:
#            branches:
#              only: dev
#      - publish_next:
#          requires:
#            - test
#          filters:
#            branches:
#              only: dev